services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: maisleitura
    volumes:
      - db_data:/var/lib/postgresql/data
  pga:
    image: dpage/pgadmin4:6.21
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: emailqualquer@gmail.com
      PGADMIN_DEFAULT_PASSWORD: user
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: 1
    depends_on:
      - db
volumes:
  db_data:
    driver: local
